spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: 
        credential:
          client-id: 
          client-secret: 
server:
  port: 9191
  forward-headers-strategy: native
  #varma
  