spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: 6a574231-a96f-4635-befa-77b5a19166d8
        credential:
          client-id: ddcb2238-3c22-4c15-9c13-119b51f30a2c
          client-secret: 0Xl8Q~EnMwpQBTZSZH8Lce7VeLlkGPhmyJK0TddQ
server:
  port: 9191
  forward-headers-strategy: native
  #varma
  